// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d0e5106a-df16-4161-b12e-e681e81f6824",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_TYU5uWSlr",
    "aws_user_pools_web_client_id": "4p0b46tfqb5i0128b37o2tak8s"
};


export default awsmobile;
